### ISSUE TITLE
Error: "AppCheck" plugin is not implemented on android

### ISSUE THREAD

**Issue by cyrildiagne** [mattmilan-dev/capacitor-firebase-appcheck#3]
Hi,

Thank you for this plugin!

I've installed `capacitor-firebase-appcheck` v1.0.10 with capacitor v3.3.2 but when I try to import the library I get this error:

```
Error: "AppCheck" plugin is not implemented on android
```

I tried following the [Plugin Not Implemented](https://capacitorjs.com/docs/android/troubleshooting#plugin-not-implemented) Troubleshoot instructions but to no avail.

Is there something else that could cause this problem?

**Comment by mattmilan-dev** [comment]
Hey cyril,

Apologies for the delay in getting back to you. Unfortunately i'm not too sure about the problem. It is still working fine in my projects but that's not to say it's perfect. 

Is it possible you could check around your android files, particulally the `android > app > src > main > assets > capacitor.plugins.json` file to see if the following exists:
```json
{
  "pkg": "capacitor-firebase-appcheck",
  "classpath": "studio.devleaf.capacitorfirebaseappcheck.AppCheckPlugin"
}
```

I did alot of work with the plugin directly in my application so it is possible that something i coded directly into the app is missing from the plugin repo.

When i get the opportunity i'll create a vanilla capacitor project and compare to see if there's anything different between my production app and the test project, but until then feel free to share anything you may find.

**Comment by mattmilan-dev** [comment]
Closed due to lack of reply.
